---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
  namespace: services
  labels:
    app: ticket-api
    service: api
    framework: flask
  annotations:
    a8r.io/description: "API service for CRUD operations on tickets"
    a8r.io/owner: renatodamas

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ticket-api

  # update each pod at a time
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0

  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - name: ticket-api
          image: ticket-manager:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ticket-configmap
            - secretRef:
                name: ticket-secret
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 516Mi
      restartPolicy: Always
