---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ticket-service-postgres
  annotations:
    a8r.io/description: "Properties for postgres connection"
stringData:

  PGUSER: ticketpg
  PGPASSWORD: ...
  PGHOST: ha-postgres
  PGPORT: "5432"
  PGDATABASE: ticket-service

  # database connection
  SQLALCHEMY_DATABASE_URI: postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)
